# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: quay.io/fenicsproject/dev-env-trilinos:latest
image: chrisrichardson/pyrol-testing:latest

pipelines:
  default:
    - step:
        script:
          - python3 setup.py build --debug
          - export PYTHONPATH=$(pwd)/build/lib.linux-x86_64-3.5:$PYTHONPATH
          - python3 -m pytest tests/test_std_vector.py
          - python3 -m pytest tests/test_dolfin_vector.py
          - . /home/fenics/firedrake/bin/activate
          - unset PETSC_DIR
          - cd ../examples/motherproblem/
          - python ../../utils/pylit/pylit.py motherproblem.py.rst
          - python motherproblem.py
          - deactivate
