# This is a sample build configuration for C++.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: quay.io/fenicsproject/dev-env-trilinos:latest
image: chrisrichardson/pyrol-testing:latest

pipelines:
  default:
    - step:
        script:
          - pip2 install pybind11           # FIXME - python2/3 issue
          - export TRILINOS_DIR=/usr/local
          - cd src
          - python setup.py install
          - cd ..
          - source /home/fenics/fenics.env.conf
          - py.test -s tests
          - . /home/fenics/firedrake/bin/activate
	      - for file in examples/*/*.py.rst; do python utils/pylit/pylit.py $$file; done
          - cd examples/motherproblem/
          - python motherproblem.py
          - deactivate
          - cd ../stokes_topology_optimization
          - python stokes_topology_optimization.py
